export const SneakerRarerity = {
  Common: 'Common',
  Uncommon: 'Uncommon',
  Rare: 'Rare',
  Epic: 'Epic',
  Legendary: 'Legendary',
} as const
export type SneakerRarerity = typeof SneakerRarerity[keyof typeof SneakerRarerity]

export const SneakerRarerityColor = {
  [SneakerRarerity.Common]: 'rgba(230, 230, 230)',
  [SneakerRarerity.Uncommon]: 'rgb(194, 255, 197)',
  [SneakerRarerity.Rare]: 'rgb(181, 224, 255)',
  [SneakerRarerity.Epic]: 'rgb(226, 191, 255)',
  [SneakerRarerity.Legendary]: 'rgb(255, 225, 173)',
} as const

export const ShoeBoxRarerityMatrix = {
  [SneakerRarerity.Common]: {
    [SneakerRarerity.Common]: 0.97,
    [SneakerRarerity.Uncommon]: 0.03,
    [SneakerRarerity.Rare]: 0,
    [SneakerRarerity.Epic]: 0,
    [SneakerRarerity.Legendary]: 0,
  },
  [SneakerRarerity.Uncommon]: {
    [SneakerRarerity.Common]: 0.25,
    [SneakerRarerity.Uncommon]: 0.73,
    [SneakerRarerity.Rare]: 0.2,
    [SneakerRarerity.Epic]: 0,
    [SneakerRarerity.Legendary]: 0,
  },
  [SneakerRarerity.Rare]: {
    [SneakerRarerity.Common]: 0,
    [SneakerRarerity.Uncommon]: 0.27,
    [SneakerRarerity.Rare]: 0.71,
    [SneakerRarerity.Epic]: 0.02,
    [SneakerRarerity.Legendary]: 0,
  },
  [SneakerRarerity.Epic]: {
    [SneakerRarerity.Common]: 0,
    [SneakerRarerity.Uncommon]: 0,
    [SneakerRarerity.Rare]: 0.3,
    [SneakerRarerity.Epic]: 0.68,
    [SneakerRarerity.Legendary]: 0.02,
  },
  [SneakerRarerity.Legendary]: {
    [SneakerRarerity.Common]: 0,
    [SneakerRarerity.Uncommon]: 0,
    [SneakerRarerity.Rare]: 0,
    [SneakerRarerity.Epic]: 0.35,
    [SneakerRarerity.Legendary]: 0.65,
  },
} as const

export const MintedSneakerShoeboxRarerityMatrix = {
  [SneakerRarerity.Common]: {
    [SneakerRarerity.Common]: {
      [SneakerRarerity.Common]: 1,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0,
      [SneakerRarerity.Epic]: 0,
      [SneakerRarerity.Legendary]: 0,
    },
    [SneakerRarerity.Uncommon]: {
      [SneakerRarerity.Common]: 0.5,
      [SneakerRarerity.Uncommon]: 0.49,
      [SneakerRarerity.Rare]: 0.01,
      [SneakerRarerity.Epic]: 0,
      [SneakerRarerity.Legendary]: 0,
    },
    [SneakerRarerity.Rare]: {
      [SneakerRarerity.Common]: 0.5,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0.49,
      [SneakerRarerity.Epic]: 0.01,
      [SneakerRarerity.Legendary]: 0,
    },
    [SneakerRarerity.Epic]: {
      [SneakerRarerity.Common]: 0.5,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0,
      [SneakerRarerity.Epic]: 0.49,
      [SneakerRarerity.Legendary]: 0.01,
    },
    [SneakerRarerity.Legendary]: {
      [SneakerRarerity.Common]: 0.5,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0,
      [SneakerRarerity.Epic]: 0,
      [SneakerRarerity.Legendary]: 0.5,
    },
  },
  [SneakerRarerity.Uncommon]: {
    [SneakerRarerity.Common]: {
      [SneakerRarerity.Common]: 0.5,
      [SneakerRarerity.Uncommon]: 0.49,
      [SneakerRarerity.Rare]: 0.01,
      [SneakerRarerity.Epic]: 0,
      [SneakerRarerity.Legendary]: 0,
    },
    [SneakerRarerity.Uncommon]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0.98,
      [SneakerRarerity.Rare]: 0.02,
      [SneakerRarerity.Epic]: 0,
      [SneakerRarerity.Legendary]: 0,
    },
    [SneakerRarerity.Rare]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0.49,
      [SneakerRarerity.Rare]: 0.5,
      [SneakerRarerity.Epic]: 0.01,
      [SneakerRarerity.Legendary]: 0,
    },
    [SneakerRarerity.Epic]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0.49,
      [SneakerRarerity.Rare]: 0.01,
      [SneakerRarerity.Epic]: 0.49,
      [SneakerRarerity.Legendary]: 0.01,
    },
    [SneakerRarerity.Legendary]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0.49,
      [SneakerRarerity.Rare]: 0.01,
      [SneakerRarerity.Epic]: 0,
      [SneakerRarerity.Legendary]: 0.5,
    },
  },
  [SneakerRarerity.Rare]: {
    [SneakerRarerity.Common]: {
      [SneakerRarerity.Common]: 0.5,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0.49,
      [SneakerRarerity.Epic]: 0.01,
      [SneakerRarerity.Legendary]: 0,
    },
    [SneakerRarerity.Uncommon]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0.49,
      [SneakerRarerity.Rare]: 0.5,
      [SneakerRarerity.Epic]: 0.01,
      [SneakerRarerity.Legendary]: 0,
    },
    [SneakerRarerity.Rare]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0.98,
      [SneakerRarerity.Epic]: 0.02,
      [SneakerRarerity.Legendary]: 0,
    },
    [SneakerRarerity.Epic]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0.49,
      [SneakerRarerity.Epic]: 0.5,
      [SneakerRarerity.Legendary]: 0.01,
    },
    [SneakerRarerity.Legendary]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0.49,
      [SneakerRarerity.Epic]: 0.01,
      [SneakerRarerity.Legendary]: 0.5,
    },
  },
  [SneakerRarerity.Epic]: {
    [SneakerRarerity.Common]: {
      [SneakerRarerity.Common]: 0.5,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0,
      [SneakerRarerity.Epic]: 0.49,
      [SneakerRarerity.Legendary]: 0.01,
    },
    [SneakerRarerity.Uncommon]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0.49,
      [SneakerRarerity.Rare]: 0.01,
      [SneakerRarerity.Epic]: 0.49,
      [SneakerRarerity.Legendary]: 0.01,
    },
    [SneakerRarerity.Rare]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0.49,
      [SneakerRarerity.Epic]: 0.5,
      [SneakerRarerity.Legendary]: 0.01,
    },
    [SneakerRarerity.Epic]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0,
      [SneakerRarerity.Epic]: 0.98,
      [SneakerRarerity.Legendary]: 0.02,
    },
    [SneakerRarerity.Legendary]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0,
      [SneakerRarerity.Epic]: 0.49,
      [SneakerRarerity.Legendary]: 0.51,
    },
  },
  [SneakerRarerity.Legendary]: {
    [SneakerRarerity.Common]: {
      [SneakerRarerity.Common]: 0.5,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0,
      [SneakerRarerity.Epic]: 0,
      [SneakerRarerity.Legendary]: 0.5,
    },
    [SneakerRarerity.Uncommon]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0.49,
      [SneakerRarerity.Rare]: 0.01,
      [SneakerRarerity.Epic]: 0,
      [SneakerRarerity.Legendary]: 0.5,
    },
    [SneakerRarerity.Rare]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0.49,
      [SneakerRarerity.Epic]: 0.01,
      [SneakerRarerity.Legendary]: 0.5,
    },
    [SneakerRarerity.Epic]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0,
      [SneakerRarerity.Epic]: 0.49,
      [SneakerRarerity.Legendary]: 0.51,
    },
    [SneakerRarerity.Legendary]: {
      [SneakerRarerity.Common]: 0,
      [SneakerRarerity.Uncommon]: 0,
      [SneakerRarerity.Rare]: 0,
      [SneakerRarerity.Epic]: 0,
      [SneakerRarerity.Legendary]: 1,
    },
  },
} as const
